import { Injectable, Logger, OnModuleDestroy, OnModuleInit } from '@nestjs/common';
import { SQL, type TransactionSQL } from 'bun';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { createHash, randomBytes } from 'node:crypto';

export type DatabaseDriver = 'sqlite' | 'postgres';

@Injectable()
export class DatabaseService implements OnModuleInit, OnModuleDestroy {
  readonly driver: DatabaseDriver;
  private readonly sql: SQL;
  private queue: Promise<unknown> = Promise.resolve();
  private readonly logger = new Logger(DatabaseService.name);

  constructor() {
    const driver = process.env.DB_DRIVER || 'sqlite';
    if (driver !== 'sqlite' && driver !== 'postgres') throw new Error('DB_DRIVER debe ser sqlite o postgres.');
    this.driver = driver;
    if (driver === 'sqlite') {
      const root = path.resolve(__dirname, '../../../..');
      const directory = path.resolve(root, process.env.DATA_DIR || 'data');
      mkdirSync(directory, { recursive: true });
      this.sql = new SQL({ adapter: 'sqlite', filename: path.join(directory, 'nuwenet.sqlite') });
    } else {
      const url = process.env.DATABASE_URL;
      if (url && !/^postgres(?:ql)?:\/\//.test(url)) throw new Error('DATABASE_URL debe ser una conexión PostgreSQL.');
      const ssl = process.env.PGSSLMODE || 'disable';
      if (!['disable', 'prefer', 'require', 'verify-ca', 'verify-full'].includes(ssl)) throw new Error('PGSSLMODE inválido.');
      this.sql = url ? new SQL(url, { connectionTimeout: 10, max: 10 }) : new SQL({
        adapter: 'postgres', hostname: process.env.PGHOST || '127.0.0.1',
        port: Number(process.env.PGPORT || 5432), database: process.env.PGDATABASE || 'nuwenet',
        username: process.env.PGUSER || 'postgres', password: process.env.PGPASSWORD,
        ssl: ssl as 'disable' | 'prefer' | 'require' | 'verify-ca' | 'verify-full',
        connectionTimeout: 10, max: 10,
      });
    }
  }

  async onModuleInit() {
    if (this.driver === 'sqlite') {
      await this.sql`PRAGMA foreign_keys = ON`;
      await this.sql`PRAGMA busy_timeout = 5000`;
    }
    await this.write(async tx => {
      const id = this.driver === 'sqlite' ? 'INTEGER PRIMARY KEY' : 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
      // This migration adopts the original SQLite schema without rewriting its records.
      // Only fixed, application-owned SQL fragments are interpolated here.
      await tx.unsafe('CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY)');
      const applied = await tx`SELECT version FROM schema_migrations WHERE version=1`;
      if (!applied.length) {
      const timestamp = this.driver === 'sqlite' ? 'CURRENT_TIMESTAMP' : "(to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS'))";
      const statements = [
        `CREATE TABLE IF NOT EXISTS plans(id ${id}, name TEXT NOT NULL, down INTEGER NOT NULL, up INTEGER NOT NULL, price INTEGER NOT NULL)`,
        `CREATE TABLE IF NOT EXISTS customers(id ${id}, apartment TEXT NOT NULL UNIQUE, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', plan_id INTEGER NOT NULL REFERENCES plans(id), status TEXT NOT NULL DEFAULT 'active')`,
        `CREATE TABLE IF NOT EXISTS invoices(id ${id}, customer_id INTEGER NOT NULL REFERENCES customers(id), period TEXT NOT NULL, due TEXT NOT NULL, amount INTEGER NOT NULL, paid_at TEXT, UNIQUE(customer_id,period))`,
        `CREATE TABLE IF NOT EXISTS events(id ${id}, created_at TEXT NOT NULL DEFAULT ${timestamp}, message TEXT NOT NULL)`,
        `CREATE TABLE IF NOT EXISTS commands(id ${id}, customer_id INTEGER NOT NULL REFERENCES customers(id), action TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT ${timestamp}, mode TEXT NOT NULL DEFAULT 'simulated')`,
        'CREATE INDEX IF NOT EXISTS invoices_customer_due ON invoices(customer_id, due)',
      ];
      for (const statement of statements) await tx.unsafe(statement);
      await tx`INSERT INTO schema_migrations(version) VALUES (1)`;
      }
      const routerMigration = await tx`SELECT version FROM schema_migrations WHERE version=2`;
      if (!routerMigration.length) {
        await tx.unsafe(`CREATE TABLE routers (
          id ${id}, name TEXT NOT NULL, adapter TEXT NOT NULL, host TEXT NOT NULL,
          port INTEGER NOT NULL, protocol TEXT NOT NULL, diagnostic_host TEXT,
          credentials TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'untested',
          last_checked TEXT, last_error TEXT, snapshot TEXT,
          UNIQUE(host, port, protocol)
        )`);
        await tx.unsafe(`CREATE TABLE router_checks (
          id ${id}, router_id INTEGER NOT NULL REFERENCES routers(id) ON DELETE CASCADE,
          checked_at TEXT NOT NULL, success INTEGER NOT NULL, message TEXT NOT NULL
        )`);
        await tx`INSERT INTO schema_migrations(version) VALUES (2)`;
      }
      const customerIpMigration = await tx`SELECT version FROM schema_migrations WHERE version=3`;
      if (!customerIpMigration.length) {
        // SQLite y PostgreSQL soportan ADD COLUMN IF ausente solo vía intento; ignoramos "duplicada" si ya existe.
        try {
          await tx.unsafe('ALTER TABLE customers ADD COLUMN ip TEXT');
        } catch (error) {
          const message = (error as Error)?.message || '';
          if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
        }
        await tx.unsafe('CREATE INDEX IF NOT EXISTS customers_ip ON customers(ip)');
        await tx`INSERT INTO schema_migrations(version) VALUES (3)`;
      }
      const opsMigration = await tx`SELECT version FROM schema_migrations WHERE version=4`;
      if (!opsMigration.length) {
        await tx.unsafe(`CREATE TABLE IF NOT EXISTS users (
          id ${id}, username TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL,
          role TEXT NOT NULL DEFAULT 'admin', created_at TEXT NOT NULL
        )`);
        await tx.unsafe(`CREATE TABLE IF NOT EXISTS sessions (
          token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          created_at TEXT NOT NULL, expires_at TEXT NOT NULL
        )`);
        await tx.unsafe(`CREATE TABLE IF NOT EXISTS payments (
          id ${id}, invoice_id INTEGER NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
          amount INTEGER NOT NULL, created_at TEXT NOT NULL
        )`);
        await tx.unsafe('CREATE INDEX IF NOT EXISTS payments_invoice ON payments(invoice_id)');
        await tx.unsafe(`CREATE TABLE IF NOT EXISTS notifications (
          id ${id}, created_at TEXT NOT NULL, channel TEXT NOT NULL DEFAULT 'log',
          target TEXT NOT NULL DEFAULT '', message TEXT NOT NULL
        )`);
        await tx`INSERT INTO schema_migrations(version) VALUES (4)`;
      }
      const reliability = await tx`SELECT version FROM schema_migrations WHERE version=5`;
      if (!reliability.length) {
        const statements = [
          'ALTER TABLE users ADD COLUMN disabled INTEGER NOT NULL DEFAULT 0',
          'CREATE TABLE login_attempts (key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, resets_at TEXT NOT NULL)',
          'ALTER TABLE customers ADD COLUMN archived INTEGER NOT NULL DEFAULT 0',
          'ALTER TABLE customers ADD COLUMN manual_hold INTEGER NOT NULL DEFAULT 0',
          "ALTER TABLE customers ADD COLUMN network_state TEXT NOT NULL DEFAULT 'simulated'",
          'ALTER TABLE customers ADD COLUMN network_checked_at TEXT',
          "ALTER TABLE commands ADD COLUMN status TEXT NOT NULL DEFAULT 'simulated'",
          'ALTER TABLE commands ADD COLUMN payload TEXT',
          'ALTER TABLE commands ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0',
          'ALTER TABLE commands ADD COLUMN next_attempt TEXT',
          'ALTER TABLE commands ADD COLUMN last_error TEXT',
          "ALTER TABLE payments ADD COLUMN method TEXT NOT NULL DEFAULT 'cash'",
          "ALTER TABLE payments ADD COLUMN reference TEXT NOT NULL DEFAULT ''",
          'ALTER TABLE payments ADD COLUMN actor_id INTEGER REFERENCES users(id)',
          'ALTER TABLE payments ADD COLUMN reversed_at TEXT',
          'ALTER TABLE payments ADD COLUMN reversed_by INTEGER REFERENCES users(id)',
          'ALTER TABLE payments ADD COLUMN reversal_reason TEXT',
          'ALTER TABLE payments ADD COLUMN request_key TEXT',
          'CREATE UNIQUE INDEX payments_request_key ON payments(request_key)',
          'ALTER TABLE events ADD COLUMN actor TEXT',
          'CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)',
          'CREATE TABLE task_locks (name TEXT PRIMARY KEY, token TEXT NOT NULL, expires_at TEXT NOT NULL)',
          `CREATE TABLE audit_log (id ${id}, actor_id INTEGER REFERENCES users(id), username TEXT NOT NULL, action TEXT NOT NULL, created_at TEXT NOT NULL)`,
          `CREATE TABLE reminder_deliveries (id ${id}, invoice_id INTEGER NOT NULL REFERENCES invoices(id), day TEXT NOT NULL, UNIQUE(invoice_id,day))`,
          'CREATE INDEX commands_queue ON commands(status,next_attempt,id)',
          'CREATE INDEX router_checks_router ON router_checks(router_id,id)',
          'CREATE INDEX payments_date ON payments(created_at)',
        ];
        for (const statement of statements) await tx.unsafe(statement);
        // Existing suspensions have no reliable reason: preserve them as manual holds.
        await tx`UPDATE customers SET manual_hold=1 WHERE status='suspended'`;
        // Adopt paid invoices from the pre-payments schema without losing receipts.
        await tx`INSERT INTO payments(invoice_id,amount,created_at,method,reference)
          SELECT i.id,i.amount,i.paid_at,'legacy','Saldo histórico migrado' FROM invoices i
          WHERE i.paid_at IS NOT NULL AND NOT EXISTS (SELECT 1 FROM payments p WHERE p.invoice_id=i.id)`;
        await tx`UPDATE commands SET status=CASE WHEN mode='mikrotik' THEN 'applied' WHEN mode='mikrotik-failed' THEN 'legacy_failed' ELSE 'simulated' END`;
        await tx`INSERT INTO schema_migrations(version) VALUES (5)`;
      }
      // Migración 6: base multiedificio. No rompe el modo actual de un edificio:
      // crea buildings + user_buildings y building_id nullable; siembra edificio 1
      // con lo existente y asigna a los usuarios actuales.
      const multiBuilding = await tx`SELECT version FROM schema_migrations WHERE version=6`;
      if (!multiBuilding.length) {
        await tx.unsafe(`CREATE TABLE IF NOT EXISTS buildings (
          id ${id}, name TEXT NOT NULL, created_at TEXT NOT NULL
        )`);
        await tx.unsafe(`CREATE TABLE IF NOT EXISTS user_buildings (
          user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
          building_id INTEGER NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
          PRIMARY KEY (user_id, building_id)
        )`);
        const addBuildingId = async (table: string) => {
          try { await tx.unsafe(`ALTER TABLE ${table} ADD COLUMN building_id INTEGER REFERENCES buildings(id)`); }
          catch (error) {
            const message = (error as Error)?.message || '';
            if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
          }
        };
        await addBuildingId('plans');
        await addBuildingId('customers');
        await addBuildingId('routers');
        const [count] = await tx`SELECT COUNT(*) count FROM buildings`;
        if (Number(count.count) === 0) {
          const [ops] = await tx`SELECT value FROM settings WHERE key='operations'`;
          let seedName = 'Mi edificio';
          try {
            const parsed = JSON.parse(ops?.value || '{}');
            if (typeof parsed.building_name === 'string' && parsed.building_name.trim()) seedName = parsed.building_name.trim().slice(0, 100);
          } catch { /* conserva el nombre por defecto */ }
          const [b] = await tx`INSERT INTO buildings(name,created_at) VALUES (${seedName},${new Date().toISOString()}) RETURNING id`;
          const buildingId = (b as unknown as { id: number }).id;
          await tx`UPDATE plans SET building_id=${buildingId} WHERE building_id IS NULL`;
          await tx`UPDATE customers SET building_id=${buildingId} WHERE building_id IS NULL`;
          await tx`UPDATE routers SET building_id=${buildingId} WHERE building_id IS NULL`;
          const users = await tx`SELECT id, role FROM users`;
          for (const u of users as unknown as { id: number }[]) {
            await tx`INSERT INTO user_buildings(user_id,building_id) VALUES (${u.id},${buildingId}) ON CONFLICT(user_id,building_id) DO NOTHING`;
          }
        }
        await tx`INSERT INTO schema_migrations(version) VALUES (6)`;
      }
      // Migración 7: equipo central por edificio. El ajuste global sigue como
      // valor heredado; cada edificio puede tener su propio MikroTik central.
      const centralPerBuilding = await tx`SELECT version FROM schema_migrations WHERE version=7`;
      if (!centralPerBuilding.length) {
        try { await tx.unsafe('ALTER TABLE buildings ADD COLUMN central_router_id INTEGER REFERENCES routers(id)'); }
        catch (error) {
          const message = (error as Error)?.message || '';
          if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
        }
        try {
          const [ops] = await tx`SELECT value FROM settings WHERE key='operations'`;
          const globalCentral = JSON.parse(ops?.value || '{}').central_router_id;
          if (Number.isInteger(globalCentral)) {
            await tx`UPDATE buildings SET central_router_id=${globalCentral} WHERE central_router_id IS NULL`;
          }
        } catch { /* sin central global: los edificios quedan simulados */ }
        await tx`INSERT INTO schema_migrations(version) VALUES (7)`;
      }
    });
    // Migración 8: departamento único por edificio, no global. Antes `apartment`
    // era UNIQUE en toda la tabla y dos edificios no podían repetir el "101".
    // Va fuera de la transacción anterior porque en SQLite reconstruye la tabla
    // (DROP con FK activas fallaría dentro de la transacción).
    await this.migrateCustomerScope();
    // Migración 9: el super-admin no se vincula a ningún edificio (ve todo por
    // rol). Limpia asignaciones heredadas de versiones anteriores.
    const superLinks = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=9`);
    if (!superLinks.length) {
      await this.write(tx => tx`DELETE FROM user_buildings WHERE user_id IN (SELECT id FROM users WHERE role='superadmin')`);
      await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (9)`);
    }
    // Migración 10: dirección del edificio.
    const buildingAddress = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=10`);
    if (!buildingAddress.length) {
      try { await this.write(tx => tx.unsafe(`ALTER TABLE buildings ADD COLUMN address TEXT NOT NULL DEFAULT ''`)); }
      catch (error) {
        const message = (error as Error)?.message || '';
        if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
      }
      await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (10)`);
    }
    // Migración 12: activar/desactivar edificios y routers.
    const toggles = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=12`);
    if (!toggles.length) {
      const addFlag = async (table: string) => {
        try { await this.write(tx => tx.unsafe(`ALTER TABLE ${table} ADD COLUMN disabled INTEGER NOT NULL DEFAULT 0`)); }
        catch (error) {
          const message = (error as Error)?.message || '';
          if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
        }
      };
      await addFlag('buildings');
      await addFlag('routers');
      await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (12)`);
    }
    // Migración 11: datos del administrador (CI, nombres, dirección, teléfono).
    const adminProfile = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=11`);
    if (!adminProfile.length) {
      const addColumn = async (definition: string) => {
        try { await this.write(tx => tx.unsafe(`ALTER TABLE users ADD COLUMN ${definition}`)); }
        catch (error) {
          const message = (error as Error)?.message || '';
          if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
        }
      };
      await addColumn(`ci TEXT NOT NULL DEFAULT ''`);
      await addColumn(`first_name TEXT NOT NULL DEFAULT ''`);
      await addColumn(`last_name TEXT NOT NULL DEFAULT ''`);
      await addColumn(`address TEXT NOT NULL DEFAULT ''`);
      await addColumn(`phone TEXT NOT NULL DEFAULT ''`);
      await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (11)`);
    }
    await this.write(async tx => {
      if ((await tx`SELECT version FROM schema_migrations WHERE version=13`).length) return;
      // Historical rows have no reliable scope. Keep them global, visible only to the system owner.
      // Idempotente: ignora columnas/índices ya existentes si se reintenta tras un fallo parcial.
      await this.safeAlter(tx, 'ALTER TABLE events ADD COLUMN building_id INTEGER');
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN building_id INTEGER');
      await tx.unsafe('CREATE INDEX IF NOT EXISTS events_building_id ON events(building_id,id)');
      await tx.unsafe('CREATE INDEX IF NOT EXISTS notifications_building_id ON notifications(building_id,id)');
      await tx`INSERT INTO schema_migrations(version) VALUES (13)`;
    });
    await this.write(async tx => {
      if ((await tx`SELECT version FROM schema_migrations WHERE version=14`).length) return;
      const [row] = await tx`SELECT value FROM settings WHERE key='operations'`;
      if (row) {
        const config = JSON.parse(row.value);
        delete config.central_router_id;
        await tx`UPDATE settings SET value=${JSON.stringify(config)} WHERE key='operations'`;
      }
      await tx.unsafe(`CREATE TABLE IF NOT EXISTS customer_devices (
        router_id INTEGER NOT NULL REFERENCES routers(id) ON DELETE CASCADE,
        mac TEXT NOT NULL,
        customer_id INTEGER NOT NULL REFERENCES customers(id),
        created_at TEXT NOT NULL,
        PRIMARY KEY(router_id,mac))`);
      await tx.unsafe('CREATE INDEX IF NOT EXISTS customer_devices_customer ON customer_devices(customer_id)');
      await tx`INSERT INTO schema_migrations(version) VALUES (14)`;
    });
    await this.write(async tx=>{
      if((await tx`SELECT version FROM schema_migrations WHERE version=15`).length)return;
      await tx.unsafe('CREATE TABLE IF NOT EXISTS customer_network_targets(router_id INTEGER NOT NULL REFERENCES routers(id),ip TEXT NOT NULL,customer_id INTEGER NOT NULL REFERENCES customers(id),PRIMARY KEY(router_id,ip))');
      await tx.unsafe('CREATE TABLE IF NOT EXISTS customer_network_dirty(customer_id INTEGER PRIMARY KEY REFERENCES customers(id))');
      await tx`INSERT INTO customer_network_dirty(customer_id) SELECT DISTINCT customer_id FROM customer_devices`;
      await this.safeAlter(tx, "ALTER TABLE notifications ADD COLUMN delivery_status TEXT NOT NULL DEFAULT 'internal'");
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN attempts INTEGER NOT NULL DEFAULT 0');
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN next_attempt TEXT');
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN last_error TEXT');
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN delivered_at TEXT');
      await tx`INSERT INTO schema_migrations(version) VALUES (15)`;
    });
    await this.write(async tx=>{
      if((await tx`SELECT version FROM schema_migrations WHERE version=16`).length)return;
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN provider_id TEXT');
      await this.safeAlter(tx, 'ALTER TABLE notifications ADD COLUMN read_at TEXT');
      await tx.unsafe('CREATE INDEX IF NOT EXISTS notifications_provider_id ON notifications(provider_id)');
      await tx.unsafe('CREATE TABLE IF NOT EXISTS whatsapp_receipts(provider_id TEXT PRIMARY KEY,state TEXT NOT NULL,event_at TEXT NOT NULL,received_at TEXT NOT NULL)');
      await tx`INSERT INTO schema_migrations(version) VALUES (16)`;
    });
    await this.write(async tx => {
      if ((await tx`SELECT version FROM schema_migrations WHERE version=17`).length) return;
      const id = this.driver === 'sqlite' ? 'INTEGER PRIMARY KEY' : 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
      try {
        await tx.unsafe('ALTER TABLE customers ADD COLUMN access_token TEXT');
      } catch (error) {
        const message = (error as Error)?.message || '';
        if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
      }
      await tx.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_access_token ON customers(access_token)');
      const existing = await tx<{ id: number; access_token: string | null }[]>`SELECT id, access_token FROM customers WHERE access_token IS NULL`;
      for (const c of existing) {
        const token = randomBytes(32).toString('base64url');
        await tx`UPDATE customers SET access_token=${token} WHERE id=${c.id}`;
      }
      await tx.unsafe(`CREATE TABLE IF NOT EXISTS payment_reports (
        id ${id},
        customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        amount INTEGER NOT NULL,
        reference TEXT NOT NULL DEFAULT '',
        notes TEXT NOT NULL DEFAULT '',
        status TEXT NOT NULL DEFAULT 'pending',
        created_at TEXT NOT NULL
      )`);
      await tx.unsafe('CREATE INDEX IF NOT EXISTS payment_reports_customer ON payment_reports(customer_id, created_at)');
      await tx`INSERT INTO schema_migrations(version) VALUES (17)`;
    });
    await this.write(async tx => {
      await tx`INSERT INTO settings(key,value) VALUES ('receipt-signature-key',${randomBytes(32).toString('hex')}) ON CONFLICT(key) DO NOTHING`;
    });
    // Migración 18: plan opcional en departamentos (plan_id nullable).
    await this.migratePlanOptional();
    // Migración 20: building_id obligatorio en departamentos. Con NULL, el
    // UNIQUE(building_id, apartment) no frena duplicados (NULL ≠ NULL).
    await this.migrateCustomerBuildingNotNull();
    await this.write(async tx=>{
      if((await tx`SELECT version FROM schema_migrations WHERE version=19`).length)return;
      const id=this.driver==='sqlite'?'INTEGER PRIMARY KEY':'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
      await tx.unsafe(`CREATE TABLE usage_cursors (
        router_id INTEGER NOT NULL REFERENCES routers(id) ON DELETE CASCADE,
        customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        queue_name TEXT NOT NULL, queue_id TEXT,
        download_bytes BIGINT NOT NULL, upload_bytes BIGINT NOT NULL,
        observed_at TEXT NOT NULL, missing INTEGER NOT NULL DEFAULT 0,
        PRIMARY KEY(router_id,customer_id,queue_name))`);
      await tx.unsafe(`CREATE TABLE usage_daily (
        customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        day TEXT NOT NULL, download_bytes BIGINT NOT NULL DEFAULT 0,
        upload_bytes BIGINT NOT NULL DEFAULT 0, samples INTEGER NOT NULL DEFAULT 0,
        resets INTEGER NOT NULL DEFAULT 0, gaps INTEGER NOT NULL DEFAULT 0,
        estimated_bytes BIGINT NOT NULL DEFAULT 0, PRIMARY KEY(customer_id,day))`);
      await tx.unsafe(`CREATE TABLE usage_events (
        id ${id},customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
        detected_at TEXT NOT NULL,kind TEXT NOT NULL)`);
      await tx.unsafe('CREATE INDEX usage_events_customer_time ON usage_events(customer_id,detected_at)');
      await tx.unsafe(`CREATE TABLE usage_router_state (
        router_id INTEGER PRIMARY KEY REFERENCES routers(id) ON DELETE CASCADE,
        last_attempt TEXT NOT NULL,last_success TEXT,status TEXT NOT NULL)`);
      await tx`INSERT INTO schema_migrations(version) VALUES (19)`;
    });
    await this.write(async tx=>{
      if((await tx`SELECT version FROM schema_migrations WHERE version=21`).length)return;
      // B1: ciclo de vida del enlace del residente. Los enlaces existentes se
      // conservan sin caducidad; solo se registra su emisión para auditoría.
      await this.safeAlter(tx, 'ALTER TABLE customers ADD COLUMN access_issued_at TEXT');
      await this.safeAlter(tx, 'ALTER TABLE customers ADD COLUMN access_expires_at TEXT');
      await this.safeAlter(tx, 'ALTER TABLE customers ADD COLUMN access_version INTEGER NOT NULL DEFAULT 1');
      const stamp = new Date().toISOString();
      await tx`UPDATE customers SET access_issued_at=COALESCE(access_issued_at,${stamp}) WHERE access_issued_at IS NULL`;
      await tx`INSERT INTO schema_migrations(version) VALUES (21)`;
    });
    await this.write(async tx=>{
      if((await tx`SELECT version FROM schema_migrations WHERE version=22`).length)return;
      // B5: el enlace completo solo existe al emitirlo; en reposo solo su hash.
      // Migra los enlaces existentes calculando su hash para preservar validez.
      await this.safeAlter(tx, 'ALTER TABLE customers ADD COLUMN access_token_hash TEXT');
      const legacy = await tx<{ id: number; access_token: string | null; access_token_hash: string | null }[]>`SELECT id, access_token, access_token_hash FROM customers WHERE access_token_hash IS NULL AND access_token IS NOT NULL`;
      for (const row of legacy) {
        const hash = createHash('sha256').update(row.access_token as string).digest('hex');
        await tx`UPDATE customers SET access_token_hash=${hash} WHERE id=${row.id}`;
      }
      await tx.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_access_token_hash ON customers(access_token_hash)');
      await tx`INSERT INTO schema_migrations(version) VALUES (22)`;
    });
    await this.write(async tx=>{
      if((await tx`SELECT version FROM schema_migrations WHERE version=23`).length)return;
      // B8/B9: auditoría estructurada (sin secretos) + registro de seguridad
      // independiente del rollback del negocio. Retención: 180 días.
      await this.safeAlter(tx, 'ALTER TABLE audit_log ADD COLUMN building_id INTEGER');
      await this.safeAlter(tx, "ALTER TABLE audit_log ADD COLUMN operation TEXT NOT NULL DEFAULT ''");
      await this.safeAlter(tx, "ALTER TABLE audit_log ADD COLUMN resource TEXT NOT NULL DEFAULT ''");
      await this.safeAlter(tx, "ALTER TABLE audit_log ADD COLUMN result TEXT NOT NULL DEFAULT ''");
      await this.safeAlter(tx, "ALTER TABLE audit_log ADD COLUMN correlation_id TEXT NOT NULL DEFAULT ''");
      const id = this.driver === 'sqlite' ? 'INTEGER PRIMARY KEY' : 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
      await tx.unsafe(`CREATE TABLE IF NOT EXISTS security_events (
        id ${id}, created_at TEXT NOT NULL, actor TEXT NOT NULL,
        ip TEXT NOT NULL DEFAULT '', event TEXT NOT NULL, detail TEXT NOT NULL DEFAULT '')`);
      await tx.unsafe('CREATE INDEX IF NOT EXISTS security_events_created ON security_events(created_at)');
      await tx.unsafe('CREATE INDEX IF NOT EXISTS audit_log_created ON audit_log(created_at)');
      await tx`INSERT INTO schema_migrations(version) VALUES (23)`;
    });
    await this.write(async tx=>{
      // B5 (reparación, corre en cada arranque): calcula el hash de filas
      // heredadas con plain válido y emite enlaces nuevos para las filas sin
      // hash utilizable. Corre aquí porque access_token_hash existe desde v22.
      const legacy = await tx<{ id: number; access_token: string }[]>`SELECT id, access_token FROM customers WHERE access_token_hash IS NULL AND access_token IS NOT NULL AND length(access_token)>=43`;
      for (const row of legacy) {
        await tx`UPDATE customers SET access_token_hash=${createHash('sha256').update(row.access_token).digest('hex')} WHERE id=${row.id}`;
      }
      const rows = await tx<{ id: number }[]>`SELECT id FROM customers WHERE access_token_hash IS NULL AND (access_token IS NULL OR length(access_token)<43)`;
      for (const row of rows) {
        const fresh = randomBytes(32).toString('base64url');
        await tx`UPDATE customers SET access_token=${null},access_token_hash=${createHash('sha256').update(fresh).digest('hex')} WHERE id=${row.id}`;
      }
    });
    this.logger.log(`Base de datos preparada: ${this.driver}.`);
  }

  private async migratePlanOptional() {
    const done = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=18`);
    if (done.length) return;
    if (this.driver === 'postgres') {
      await this.write(async tx => {
        await tx.unsafe('ALTER TABLE customers ALTER COLUMN plan_id DROP NOT NULL');
        await tx`INSERT INTO schema_migrations(version) VALUES (18)`;
      });
      return;
    }
    const [table] = await this.read(tx => tx<{ sql: string }[]>`SELECT sql FROM sqlite_master WHERE name='customers'`);
    const needsFix = /plan_id\s+INTEGER\s+NOT\s+NULL/i.test(table?.sql || '');
    if (!needsFix) {
      await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (18)`);
      return;
    }
    await this.serialize(async () => {
      await this.sql.unsafe('PRAGMA foreign_keys=OFF');
      try {
        await this.sql.unsafe('BEGIN IMMEDIATE');
        try {
          // Reconstruye la tabla conservando todas las columnas actuales: se parsea el
          // DDL vigente y solo se relaja plan_id a nullable. Así futuras columnas
          // agregadas por otras migraciones no se pierden en la copia.
          const ddl = table?.sql || '';
          const body = ddl.slice(ddl.indexOf('(') + 1, ddl.lastIndexOf(')'));
          const parts: string[] = [];
          for (const chunk of body.split(/,(?![^(]*\))/)) {
            const def = chunk.trim();
            if (!def || /^UNIQUE\s*\(/i.test(def) || /^PRIMARY\s+KEY/i.test(def) || /^FOREIGN\s+KEY/i.test(def) || /^CONSTRAINT\s/i.test(def)) continue;
            parts.push(/^plan_id\b/i.test(def) ? 'plan_id INTEGER REFERENCES plans(id)' : def);
          }
          const cols = parts.map(d => d.split(/\s+/)[0].replace(/["'`[\]]/g, ''));
          await this.sql.unsafe(`CREATE TABLE customers_new(${[...parts, 'UNIQUE(building_id, apartment)'].join(', ')})`);
          await this.sql.unsafe(`INSERT INTO customers_new(${cols.join(',')}) SELECT ${cols.join(',')} FROM customers`);
          await this.sql.unsafe('DROP TABLE customers');
          await this.sql.unsafe('ALTER TABLE customers_new RENAME TO customers');
          await this.sql.unsafe('CREATE INDEX IF NOT EXISTS customers_ip ON customers(ip)');
          await this.sql.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_access_token ON customers(access_token)');
          await this.sql.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_building_apartment ON customers(building_id, apartment)');
          await this.sql.unsafe('COMMIT');
        } catch (error) { try { await this.sql.unsafe('ROLLBACK'); } catch { /* sin transacción que revertir */ } throw error; }
      } finally { await this.sql.unsafe('PRAGMA foreign_keys=ON'); }
    });
    await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (18)`);
  }

  private async migrateCustomerBuildingNotNull() {
    const done = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=20`);
    if (done.length) return;
    const mark = () => this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (20)`);
    const [first] = await this.read(tx => tx<{ id: number }[]>`SELECT id FROM buildings ORDER BY id LIMIT 1`);
    if (!first) { await mark(); return; }
    await this.write(async tx => {
      await tx`UPDATE customers SET building_id=${first.id} WHERE building_id IS NULL`;
      await tx`UPDATE plans SET building_id=${first.id} WHERE building_id IS NULL`;
      await tx`UPDATE routers SET building_id=${first.id} WHERE building_id IS NULL`;
    });
    if (this.driver === 'postgres') {
      await this.write(async tx => {
        await tx.unsafe('ALTER TABLE customers ALTER COLUMN building_id SET NOT NULL');
        await tx`INSERT INTO schema_migrations(version) VALUES (20)`;
      });
      return;
    }
    const [table] = await this.read(tx => tx<{ sql: string }[]>`SELECT sql FROM sqlite_master WHERE name='customers'`);
    if (!/building_id\s+INTEGER\s+NOT\s+NULL/i.test(table?.sql || '')) {
      await this.serialize(async () => {
        await this.sql.unsafe('PRAGMA foreign_keys=OFF');
        try {
          await this.sql.unsafe('BEGIN IMMEDIATE');
          try {
            const ddl = table?.sql || '';
            const body = ddl.slice(ddl.indexOf('(') + 1, ddl.lastIndexOf(')'));
            const parts: string[] = [];
            for (const chunk of body.split(/,(?![^(]*\))/)) {
              const def = chunk.trim();
              if (!def || /^UNIQUE\s*\(/i.test(def) || /^PRIMARY\s+KEY/i.test(def) || /^FOREIGN\s+KEY/i.test(def) || /^CONSTRAINT\s/i.test(def)) continue;
              parts.push(/^building_id\b/i.test(def) ? 'building_id INTEGER NOT NULL REFERENCES buildings(id)' : def);
            }
            const cols = parts.map(d => d.split(/\s+/)[0].replace(/["'`[\]]/g, ''));
            await this.sql.unsafe(`CREATE TABLE customers_new(${[...parts, 'UNIQUE(building_id, apartment)'].join(', ')})`);
            await this.sql.unsafe(`INSERT INTO customers_new(${cols.join(',')}) SELECT ${cols.join(',')} FROM customers`);
            await this.sql.unsafe('DROP TABLE customers');
            await this.sql.unsafe('ALTER TABLE customers_new RENAME TO customers');
            await this.sql.unsafe('CREATE INDEX IF NOT EXISTS customers_ip ON customers(ip)');
            await this.sql.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_access_token ON customers(access_token)');
            await this.sql.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_building_apartment ON customers(building_id, apartment)');
            await this.sql.unsafe('COMMIT');
          } catch (error) { try { await this.sql.unsafe('ROLLBACK'); } catch { /* sin transacción que revertir */ } throw error; }
        } finally { await this.sql.unsafe('PRAGMA foreign_keys=ON'); }
      });
    }
    await mark();
  }

  private async migrateCustomerScope() {
    const done = await this.read(tx => tx`SELECT version FROM schema_migrations WHERE version=8`);
    if (done.length) return;
    if (this.driver === 'sqlite') {
      const [table] = await this.read(tx => tx<{ sql: string }[]>`SELECT sql FROM sqlite_master WHERE name='customers'`);
      const legacyGlobal = /apartment\s+TEXT\s+NOT\s+NULL\s+UNIQUE/i.test(table?.sql || '');
      const [dupes] = await this.read(tx => tx<{ n: number }[]>`SELECT COUNT(*) n FROM (SELECT apartment, building_id FROM customers GROUP BY apartment, building_id HAVING COUNT(*) > 1)`);
      await this.serialize(async () => {
        await this.sql.unsafe('PRAGMA foreign_keys=OFF');
        try {
          await this.sql.unsafe('BEGIN IMMEDIATE');
          try {
            if (Number(dupes?.n || 0) > 0) {
              await this.sql.unsafe(`UPDATE customers SET apartment = apartment || ' #' || id WHERE id IN (
                SELECT id FROM (SELECT id, ROW_NUMBER() OVER (PARTITION BY apartment, building_id ORDER BY id) rn FROM customers) WHERE rn > 1)`);
            }
            if (legacyGlobal) {
              await this.sql.unsafe(`CREATE TABLE customers_new(id INTEGER PRIMARY KEY, apartment TEXT NOT NULL, name TEXT NOT NULL,
                phone TEXT NOT NULL DEFAULT '', plan_id INTEGER NOT NULL REFERENCES plans(id), status TEXT NOT NULL DEFAULT 'active',
                ip TEXT, archived INTEGER NOT NULL DEFAULT 0, manual_hold INTEGER NOT NULL DEFAULT 0,
                network_state TEXT NOT NULL DEFAULT 'simulated', network_checked_at TEXT,
                building_id INTEGER REFERENCES buildings(id), UNIQUE(building_id, apartment))`);
              await this.sql.unsafe(`INSERT INTO customers_new(id,apartment,name,phone,plan_id,status,ip,archived,manual_hold,network_state,network_checked_at,building_id)
                SELECT id,apartment,name,phone,plan_id,status,ip,archived,manual_hold,network_state,network_checked_at,building_id FROM customers`);
              await this.sql.unsafe('DROP TABLE customers');
              await this.sql.unsafe('ALTER TABLE customers_new RENAME TO customers');
              await this.sql.unsafe('CREATE INDEX IF NOT EXISTS customers_ip ON customers(ip)');
            } else {
              await this.sql.unsafe('CREATE UNIQUE INDEX IF NOT EXISTS customers_building_apartment ON customers(building_id, apartment)');
            }
            await this.sql.unsafe('COMMIT');
          } catch (error) { try { await this.sql.unsafe('ROLLBACK'); } catch { /* sin transacción que revertir */ } throw error; }
        } finally { await this.sql.unsafe('PRAGMA foreign_keys=ON'); }
      });
      await this.write(tx => tx`INSERT INTO schema_migrations(version) VALUES (8)`);
      return;
    }
    // PostgreSQL: suelta la UNIQUE global de apartment y crea UNIQUE(building_id, apartment).
    await this.write(async tx => {
      await tx.unsafe(`UPDATE customers SET apartment = apartment || ' #' || id WHERE id IN (
        SELECT id FROM (SELECT id, ROW_NUMBER() OVER (PARTITION BY apartment, building_id ORDER BY id) rn FROM customers) t WHERE rn > 1)`);
      await tx.unsafe(`DO $$ DECLARE cname TEXT; BEGIN
        SELECT c.conname INTO cname FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid
          JOIN pg_attribute a ON a.attrelid = t.oid AND a.attnum = ANY (c.conkey)
        WHERE t.relname = 'customers' AND c.contype = 'u' AND array_length(c.conkey, 1) = 1 AND a.attname = 'apartment' LIMIT 1;
        IF cname IS NOT NULL THEN EXECUTE format('ALTER TABLE customers DROP CONSTRAINT %I', cname); END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'customers'::regclass AND conname = 'customers_building_apartment_key') THEN
          ALTER TABLE customers ADD CONSTRAINT customers_building_apartment_key UNIQUE (building_id, apartment);
        END IF;
      END $$`);
      await tx`INSERT INTO schema_migrations(version) VALUES (8)`;
    });
  }

  private async safeAlter(tx: TransactionSQL, statement: string) {
    try { await tx.unsafe(statement); }
    catch (error) {
      const message = (error as Error)?.message || '';
      if (!/duplicate column|ya existe|already exists/i.test(message)) throw error;
    }
  }

  private serialize<T>(operation: () => Promise<T>): Promise<T> {    // SQLite has one connection. Reads must also wait so they never see an in-flight write.
    const result = this.queue.then(operation);
    this.queue = result.catch(() => undefined);
    return result;
  }

  read<T>(operation: (tx: TransactionSQL) => Promise<T>): Promise<T> {
    if (this.driver === 'sqlite') return this.serialize(() => this.sql.begin(operation));
    return this.sql.begin('ISOLATION LEVEL REPEATABLE READ READ ONLY', operation);
  }

  write<T>(operation: (tx: TransactionSQL) => Promise<T>): Promise<T> {
    if (this.driver === 'sqlite') return this.serialize(() => this.sql.begin('IMMEDIATE', operation));
    return this.sql.begin(async tx => {
      // A transaction-scoped lock serializes management changes across API instances.
      // This protects payment idempotency and access decisions from concurrent requests.
      await tx`SELECT pg_advisory_xact_lock(78123, 1)`;
      return operation(tx);
    });
  }

  async onModuleDestroy() {
    await this.queue;
    await this.sql.close();
  }
  async backupSqlite(filename: string) {
    if (this.driver !== 'sqlite') throw new Error('El respaldo SQLite requiere ese motor.');
    await this.serialize(() => this.sql`VACUUM INTO ${filename}`);
  }
}
